Repository ynput/ayon-3dsmax, pull requests merged in 2024-10, with the labels that each got.

#19 Define app host name
  package.py
Labels: type: enhancement

#20 Replace the lib from the old setting in the tycache collector
  client/ayon_max/plugins/publish/collect_tycache_attributes.py
Labels: type: bug

#13 Make sure multicamera render uses correct camera
  client/ayon_max/api/lib_renderproducts.py
  client/ayon_max/api/lib_rendersettings.py
  client/ayon_max/plugins/publish/collect_render.py
  client/ayon_max/plugins/publish/save_scenes_for_cameras.py
Labels: type: bug, sponsored
